import { faArrowRight } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { Logo } from '../../components/brand/Logo'
import { SiteFooter } from '../../components/layout/SiteFooter'
import { navigate } from '../../lib/routes'

export function WelcomePage() {
  return <main className="min-h-screen bg-base-100 lg:flex"><section className="welcome-brand relative flex min-h-[40vh] flex-col justify-between overflow-hidden bg-neutral p-8 text-neutral-content lg:min-h-screen lg:w-1/2 lg:p-14"><Logo light/><div className="relative z-10"><p className="font-mono text-xs uppercase tracking-[.28em] text-neutral-content/50">A quieter place to connect</p><h1 className="mt-4 text-4xl font-semibold leading-tight tracking-[-.045em] sm:text-5xl lg:text-6xl">Share what<br/>matters.</h1></div><div className="brand-orb brand-orb-one"/><div className="brand-orb brand-orb-two"/></section><section className="flex min-h-[60vh] items-center justify-center p-7 sm:p-12 lg:min-h-screen lg:w-1/2"><div className="w-full max-w-md"><span className="badge badge-soft badge-primary mb-5">Welcome to 0xSocial</span><h2 className="text-4xl font-semibold tracking-[-.04em] text-base-content sm:text-5xl">See what’s happening.</h2><p className="mt-4 text-sm leading-7 text-base-content/55">Create an account or log in to continue.</p><div className="mt-9 flex flex-col gap-3"><button className="btn btn-primary h-12" onClick={() => navigate('/register')}>Create an account<FontAwesomeIcon icon={faArrowRight}/></button><button className="btn btn-outline h-12" onClick={() => navigate('/login')}>Log in</button></div><p className="mt-8 text-center text-xs text-base-content/40">By continuing, you agree to our <button className="link link-hover" onClick={() => navigate('/terms')}>Terms</button> and <button className="link link-hover" onClick={() => navigate('/privacy')}>Privacy Policy</button>.</p><SiteFooter/></div></section></main>
}
